Dev
Testov4/web pull request #1
Opened 2023-08-10 17:04 UTC by Testov4

727

2023-08-10 18:30 UTC, fartako requested changes

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/WebApplication.java
> +	public static void main(String[] args) {
в идейке поставь чтоб таб 4 спейса был, а то это пиздец

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/WebApplication.java
> +package eshop.web;
убери вот этот веб пакет, а сам файл пусть будет на одном уровне с остальными пакетами

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/configuration/WebSecurityConfig.java
> +    public WebSecurityConfig(MyUserDetailsService myUserDetailsService) {
конструкторы все поменяй на ломбоковские

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +    @Autowired
заменить на @RequiredArgsConstructor

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +package eshop.web.controllers;
названия всех пакетов в единством числе, controller, model, service и тд

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +import eshop.web.models.*;
в настройках идеи убери звездочки в импортах, это каловичок

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +        Category category = categoryService.findOne(id);
`categoryService.findOne(id); ` название метода полный кал, непонятно что оно делает, сделай как-нить `findCategoryById()`

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +    public String deleteCategory(@PathVariable int id){
`){`куда пробелы проебываешь

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +        if (category.getParent().getId()==0)
`getId()==0) `кодстайл полный кал, перед и после всех операторов ставь пробелы

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +        if (bindingResult.hasErrors())
не пиши так ифы, всегда ставь фигурные скобки, даже если там одна строчка будет

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +        if (category.getParent().getId()==0)
Почему именно когда айди 0, хрень какая-то с логикой

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminTools.java
> +public class AdminTools {
Если это контроллер, то в названии класса это должно быть

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminTools.java
> +    private final MyUserDetailsService myUserDetailsService;
Почему МайЮзер? Просто юзер

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/ProductController.java
> +        System.out.println("DAUN VSE NORM " +product.getName() + " koli4:" + quant);
для логирования используй @Slf4j

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/MainController.java
> +        user.getOrders().stream()
тут можно вызов .stream() убрать нах и просто форич оставить а ваще такая логика должна быть в сервисе

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/MainController.java
> +        User user = userService.getCurrent();
гетКуррент что

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/controllers/MainController.java
> +    public String search(Model model){
название метода полный кал, вон сверху у тебя тоже серч, как понять какой что делает по сигнатуре

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/models/Category.java
> +    @OneToMany(mappedBy = "parent", cascade = {CascadeType.ALL, CascadeType.PERSIST})
насколько я помню ALL уже включает в себя персист

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/models/Category.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
айдишники лучше делать в формате UUID без этого каловичка

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/models/Order.java
> +@Table(name = "\"order\"")
ебать что это

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/models/Category.java
> +    List<Category> subCategories;
куда модификатор доступа проебался

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/models/Order.java
> +    private int quantity;
используй обертки над примитивами

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/models/User.java
> +@Table(name = "\"user\"")
шо это бля

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/models/User.java
> +public class User {
полный кал что у тебя информация о секьюрности лежит вместе с бизнес информацией, если ты такого юзера будешь отдавать на фронт твоему сервису быстра настанет пизда

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/repositories/CategoryRepository.java
> +    public List<Category> findByParentNull();
название метода кал, почему у тебя файнд бай, но при этом метод ничего не принимает, еще и налл какой-то

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/repositories/CategoryRepository.java
> +    public List<Category> findByParent(Category category);
findByParentCategory()

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/repositories/CategoryRepository.java
> +    public List<Category> findByParentNull();
убери модификаторы доступа в интерфейсах все

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/repositories/ProductRepository.java
> +    public Optional<List<Product>> findByCategory(Category category);
Никогда листы не запаковывай в опншл, тебе не нужна эта лишняя обертка

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/security/AuthProviderImpl.java
> +public class AuthProviderImpl implements AuthenticationProvider {
Прописывай до конца названия файлов

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/CategoryService.java
> +public class CategoryService {
все сервис классы должны быть интерфесами имеющими имплементации

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/CategoryService.java
> +    public List<Category> findSubCategories(int id){
это должно быть findSubCategoriesById или ByParentId

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/CategoryService.java
> +        return categoryRepository.findByParent(categoryRepository.findById(id).orElse(null));
возвращать налл из сервиса это полный кал

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/CategoryService.java
> +        List<Category> subCategories = categories.stream().filter(p -> (p.getParent()!=null)).collect(Collectors.toList());
переноси все чейн операции на новую строчку, в миллион раз читабельнее будет

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/CategoryService.java
> +        List<Category> subCategories = categories.stream().filter(p -> (p.getParent()!=null)).collect(Collectors.toList());
скобка лишняя

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/CategoryService.java
> +        return subCategories;
весь этот метод мог быть одним стейтментом
`return findAll().stream()
.filter(govno)
.collect(mocha)`

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/CategoryService.java
> +@Transactional(readOnly = true)
не вешай транзакшнл над классами

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/CategoryService.java
> +    public List<Category> findAll(){
all что

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/MyUserDetailsService.java
> +        User user = userRepository.findByUsername(username);
возвращай в этом репозитории опшнл

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/MyUserDetailsService.java
> +        if (user==null)
и вместо этой проверки на налл можешь просто делать findByUsername("nigger").orElseThrow(() -> new NiggerException())

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/OrderService.java
> +    public Order newOrder(User user, Product product, String address, int quant){
название метода должно быть сказуемым

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/OrderService.java
> +        Order order = new Order();
почитай про аннотацию @Builder и убери этот кринж

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +            return null;
всегда возвращай путую коллекцию, никогда не возвращай null

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +        return products;
этот метод мог быть одним стейтментом

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +    public String isProductUnique(Integer id, String name) {
почему название метода такое будто он должен булеан возвращать

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +            if (foundProduct != null)
нах эти вложенные ифы если можно просто одним сделать
`if(productIsNIgger && foundNIgger) { }`

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +            if (foundProduct.getId()!=id){
сейм

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +        return "OK";
очевидно же что эти костыли можно заменить на тру и фолс

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +        if (products==null)
ебать и че этот иф делает

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +        List<Product> products = productRepository.findByNameContaining(name).orElse(null);
тут в орЭлс должен быть пустой лист и никаких ошибок ниже со стримами не вылетало бы

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/ProductService.java
> +        List<Product> productsWithCategory = products.stream().filter(p ->(p.getCategory()
а если категория будет null то че будет?

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/UserService.java
> +    public UserInformation findForUser(User user){
просто findUserInformation

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/UserService.java
> +        return false;
этот метод это полный пиздец, подумай как написать проще

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/UserService.java
> +        return "OK";
Вынеси все статусы в енамку и возвращай ее

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/UserService.java
> +
все эти вложенности можно упростить в миллион раз если использовать && и ||

2023-08-10 18:30 UTC, fartako commented on src/main/java/eshop/web/services/UserService.java
> +    public String isLoginAndEmailUnique(Integer id, String login, String email) {
тоже скорее всего булом можно заменить, либо как ниже написал вынести в енам

2023-08-10 18:30 UTC, fartako commented on src/main/resources/application.properties
> +spring.datasource.password=123
вынес всех твоих юзеров с их историями нахуй, ищи себя в шаболдах израиля. Не должно таких данных в кодовой базе

2023-08-10 18:30 UTC, fartako commented on src/test/java/eshop/web/WebApplicationTests.java
> +	void contextLoads() {
кто тесты писать будет бля ало, заказчик требует покрытие 90%, работать нах

2023-08-10 18:41 UTC, fartako commented on src/main/java/eshop/web/controllers/AdminController.java
> +        if (category.getParent().getId()==0)
И почему эта сервисная логика в контроллере

2023-08-12 09:14 UTC, Testov4 commented on src/main/java/eshop/web/configuration/WebSecurityConfig.java
> +    public WebSecurityConfig(MyUserDetailsService myUserDetailsService) {
done

2023-08-12 09:58 UTC, Testov4 commented on src/main/java/eshop/web/controllers/AdminController.java
> +    public String deleteCategory(@PathVariable int id){
uwu

2023-08-12 11:17 UTC, Testov4 commented on src/main/java/eshop/web/controllers/AdminController.java
> +        if (category.getParent().getId()==0)
> Почему именно когда айди 0, хрень какая-то с логикой

логика кал потому что формочка кал, я ебал переделывать форму ес честно

2023-08-12 12:31 UTC, Testov4 commented on src/main/java/eshop/web/controllers/AdminController.java
> +        if (category.getParent().getId()==0)
поправил пробелы

2023-08-12 12:35 UTC, Testov4 commented on src/main/java/eshop/web/controllers/AdminController.java
> +        if (bindingResult.hasErrors())
хороwo

2023-08-12 14:07 UTC, Testov4 commented on src/main/java/eshop/web/controllers/MainController.java
> +        user.getOrders().stream()
убрал стрим, вынес в логику в сервис, теперь просто вызываю каловичок метод

2023-08-12 14:08 UTC, Testov4 commented on src/main/java/eshop/web/controllers/MainController.java
> +        User user = userService.getCurrent();
changed to getCurrentUser

2023-08-12 14:18 UTC, Testov4 commented on src/main/java/eshop/web/controllers/MainController.java
> +    public String search(Model model){
забыл поменять

2023-08-12 14:18 UTC, Testov4 commented on src/main/java/eshop/web/models/Category.java
> +    @OneToMany(mappedBy = "parent", cascade = {CascadeType.ALL, CascadeType.PERSIST})
все так

2023-08-12 14:39 UTC, Testov4 commented on src/main/java/eshop/web/repositories/ProductRepository.java
> +    public Optional<List<Product>> findByCategory(Category category);
хорово

2023-08-12 14:48 UTC, Testov4 commented on src/main/java/eshop/web/security/AuthProviderImpl.java
> +public class AuthProviderImpl implements AuthenticationProvider {
хорошо

2023-08-12 16:03 UTC, Testov4 commented on src/main/java/eshop/web/services/CategoryService.java
> +public class CategoryService {
done

2023-08-12 16:07 UTC, Testov4 commented on src/main/java/eshop/web/services/CategoryService.java
> +        List<Category> subCategories = categories.stream().filter(p -> (p.getParent()!=null)).collect(Collectors.toList());
поправил

2023-08-12 16:25 UTC, Testov4 commented on src/main/java/eshop/web/services/CategoryService.java
> +@Transactional(readOnly = true)
простите

2023-08-12 16:27 UTC, Testov4 commented on src/main/java/eshop/web/services/CategoryService.java
> +        return subCategories;
умная обезьяна стикер

2023-08-12 16:27 UTC, Testov4 commented on src/main/java/eshop/web/services/CategoryService.java
> +    public List<Category> findAll(){
ренеймнул весь кал вроде

2023-08-12 16:39 UTC, Testov4 commented on src/main/java/eshop/web/services/MyUserDetailsService.java
> +        if (user==null)
done

2023-08-12 16:52 UTC, Testov4 commented on src/main/java/eshop/web/services/OrderService.java
> +        Order order = new Order();
почитал, надебсь норм

2023-08-12 16:54 UTC, Testov4 commented on src/main/java/eshop/web/services/ProductService.java
> +        return products;
z

2023-08-12 17:22 UTC, Testov4 commented on src/main/java/eshop/web/services/ProductService.java
> +        return "OK";
мне было лень менять во фронте этот кал, но ладно я поменялб

2023-08-12 17:26 UTC, Testov4 commented on src/main/java/eshop/web/services/ProductService.java
> +        if (products==null)
нихуя не делает и вообще строчек чет много, можно в одну, но лучше в 2 наверное потому что читабельнее будет

2023-08-12 17:37 UTC, Testov4 commented on src/main/java/eshop/web/services/ProductService.java
> +        List<Product> productsWithCategory = products.stream().filter(p ->(p.getCategory()
пися во рту будет.
        List<Product> products = productRepository.findByNameContaining(name);
        return products.stream()
            .filter(p -> category == null || p.getCategory().equals(category))
            .collect(Collectors.toList());
            
сделал как-то так ща

2023-08-12 19:16 UTC, Testov4 commented on src/main/java/eshop/web/services/UserService.java
> +        return false;
вроде подумал написал

2023-08-12 19:23 UTC, Testov4 commented on src/main/java/eshop/web/services/UserService.java
> +        return "OK";
OK

2023-08-13 14:00 UTC, delusion4 commented on src/main/java/eshop/web/models/Category.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
сделал

2023-08-13 14:36 UTC, Testov4 commented on src/main/java/eshop/web/models/User.java
> +public class User {
кал, но в падлу менять пушо фронт полетит

2023-08-14 14:35 UTC, closed without merging