Dev
Testov4/web pull request #2
Opened 2023-08-14 15:19 UTC by Testov4

эээ

2023-08-14 19:22 UTC, fartako requested changes

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/WebApplication.java
> +package eshop.web;
удали этот веб пакет и вынеси файл на уровень выше

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/WebApplication.java
> +		SpringApplication.run(WebApplication.class, args);
все еще 8 спейсов

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +public class CategoryServiceImpl implements CategoryService {
все имплементации вынеси в отдельный пакет в сервисе

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        Category parent = categoryRepository.findById(id).orElse(null);
кал

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        return categoryRepository.findByParent(parent);
сделай одним стейтментом

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        return categoryRepository.findByParentNull();
это бесполезная обертка, вызывая репу напрямую

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        return categoryRepository.findAll();
это бесполезная обертка, вызывая репу напрямую

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +            .filter(p -> (p.getParent() != null))
убери лишние скобки

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        log.info("Category {} succesfully created", category);
логи кринжовые

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +            category.setParent(null);
какой-то кал этот иф

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        categoryRepository.delete(category);
это бесполезная обертка, вызывая репу напрямую

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderService.java
> +    @Transactional
убери из интерфесов это

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderService.java
> +    Order FindOrderById(UUID id);
ебать че методы с большой буквы ало

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        return orderRepository.findAll();
бесполезная обертка

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        return orderRepository.findById(id).orElse(null);
кал + бесполезная обертка

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        orderRepository.save(order);
сейм

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        return order;
сделай одним стейтментом

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +    public Order createNewOrder(User user, Product product, String address, int quant) {
название метода кал, замени на buildOrder()

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +    @Transactional
нахуя

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +    public Order createNewOrder(User user, Product product, String address, int quant) {
quant пропиши до конца название переменной

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +            .finalPrice(product.getPrice()*quant)
это должен быть отдельный метод

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        orderRepository.delete(order);
бесполезная обертка

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductService.java
> +    List<Product> findRandomProducts(int quantity);
`int quantity ` замени везде на Integer

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        return productRepository.findAll();
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        if (quantity > products.size()) {
костыльное решение, почитай про .limit() в стримах

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        return productRepository.findByCategory(category);
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        return productRepository.findById(id).orElseThrow(() -> new CategoryNotFoundException("Category not found"));
почему где-то ты сразу бросаешь исключение а где-то возвращаешь null?

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        return productRepository.findByNameContaining(name);
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        productRepository.save(product);
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        productRepository.delete(product);
убеори

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        if (productIsNew && foundProduct != null) {
замени на опшнл и выкинь все ифы из этого метода

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +            .collect(Collectors.toList());
сделай все одним стейтментом

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserDetailsService.java
> +public class UserDetailsService implements org.springframework.security.core.userdetails.UserDetailsService {
почитай про статические импорты

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserDetailsService.java
> +        return new UserDetails(user);
сделай одним стейтментом

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        return userRepository.findAll();
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        return userRepository.findById(id).orElse(null);
кринж + убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        return userRepository.findById(id).orElse(null);
`orElse(null)` вот нахуя ты это делаешь везде, чтоб самого себя на null потом проверять?

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +            enrichNewUser(user);
не ставь new в названиях методов, тем более если там нихуя не new user

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +            String OldPassword = userRepository.findById(user.getId()).get().getPassword();
почему буква большая

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +            String OldPassword = userRepository.findById(user.getId()).get().getPassword();
что будет если findById вернет null?

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +            user.setPassword(OldPassword);
почему вообще метод с названием saveUser() что-то там делает с паролями?

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        if (id == null) {
нах в этом методе вообще id

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        userInformation.setUserId(user.getId());
почему у информации юзера есть поле userId если его всегда можно напрямую от юзера получить

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        user.getUserInformation().setUser(user);
че

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +        return vendorRepository.findAll();
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +        return vendorRepository.findById(id).orElse(null);
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +    @Transactional
где оверрайд

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +        vendorRepository.save(vendor);
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +        vendorRepository.delete(vendor);
убери

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +        if (vendorIsNew && (foundVendor != null)) {
используй опшнл

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +        boolean vendorIsNew = (id == null);
убери эту переменную и не используй такую форму записи

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/util/CategoryNotFoundException.java
> +import org.webjars.NotFoundException;
ебать это что, кастомные исключения не так делаются

2023-08-14 19:22 UTC, fartako commented on src/test/java/eshop/web/service/UserServiceImplTest.java
> +        return List.of(firstUser, secondUser);
это типа тест?

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/WebApplication.java
> +public class WebApplication {
куда делся проперти файл, как челы должны собирать этот проект?

2023-08-14 19:22 UTC, fartako commented on src/main/java/eshop/web/configuration/WebSecurityConfig.java
> +//
убери это

2023-08-14 20:17 UTC, Testov4 commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        Category parent = categoryRepository.findById(id).orElse(null);
потер попу

2023-08-14 20:29 UTC, Testov4 commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +public class CategoryServiceImpl implements CategoryService {
вынес

2023-08-14 20:30 UTC, Testov4 commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        return categoryRepository.findByParent(parent);
сделал

2023-08-14 20:32 UTC, delusion4 commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +            .filter(p -> (p.getParent() != null))
убрал

2023-08-14 20:43 UTC, Testov4 commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +            category.setParent(null);
убрал

2023-08-14 20:43 UTC, Testov4 commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        log.info("Category {} succesfully created", category);
(

2023-08-14 20:43 UTC, Testov4 commented on src/main/java/eshop/web/service/CategoryServiceImpl.java
> +        categoryRepository.delete(category);
юзается в контроллере

2023-08-14 20:44 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderService.java
> +    @Transactional
забыл тут убрать

2023-08-14 20:46 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderService.java
> +    Order FindOrderById(UUID id);
жестко насрал прости

2023-08-14 20:46 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        return orderRepository.findAll();
используется в контроллере

2023-08-14 20:47 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        return orderRepository.findById(id).orElse(null);
![image](https://github.com/Testov4/web/assets/35634384/afe4b972-ac2a-48fb-ab50-fc0a14eb6131)

2023-08-14 20:49 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        return orderRepository.findById(id).orElse(null);
null yBral

2023-08-14 20:50 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        orderRepository.save(order);
![image](https://github.com/Testov4/web/assets/35634384/4cae4d17-7eaf-43ad-b30b-d33dc331b878)

2023-08-14 20:52 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        return order;
done

2023-08-14 20:57 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +            .finalPrice(product.getPrice()*quant)
done

2023-08-14 20:57 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +    public Order createNewOrder(User user, Product product, String address, int quant) {
done

2023-08-14 20:58 UTC, Testov4 commented on src/main/java/eshop/web/service/OrderServiceImpl.java
> +        orderRepository.delete(order);
данная обертка используется внутри двух контроллеров

2023-08-14 21:00 UTC, Testov4 commented on src/main/java/eshop/web/service/ProductService.java
> +    List<Product> findRandomProducts(int quantity);
done

2023-08-14 21:01 UTC, Testov4 commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        return productRepository.findAll();
V konrollere

2023-08-14 21:05 UTC, Testov4 commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        if (quantity > products.size()) {
ахуеть чувак

2023-08-14 21:17 UTC, Testov4 commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        return productRepository.findById(id).orElseThrow(() -> new CategoryNotFoundException("Category not found"));
бд логика кал была, вроде пофиксил

2023-08-14 22:14 UTC, Testov4 commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +        if (productIsNew && foundProduct != null) {
return productRepository.findByName(name)
            .map(product -> product.getId().equals(id))
            .orElse(true);
            
            это ахуенно

2023-08-15 07:58 UTC, Testov4 commented on src/main/java/eshop/web/service/ProductServiceImpl.java
> +            .collect(Collectors.toList());
done

2023-08-15 07:59 UTC, Testov4 commented on src/main/java/eshop/web/service/UserDetailsService.java
> +        return new UserDetails(user);
done

2023-08-15 08:00 UTC, delusion4 commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        return userRepository.findAll();
V kontrollere

2023-08-15 08:12 UTC, Testov4 commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        return userRepository.findById(id).orElse(null);
кринж убран

2023-08-15 08:13 UTC, Testov4 commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +            enrichNewUser(user);
בסדר

2023-08-15 08:28 UTC, Testov4 commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +            String OldPassword = userRepository.findById(user.getId()).get().getPassword();
будет кал, вроде пофиксил

2023-08-15 08:32 UTC, Testov4 commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +            user.setPassword(OldPassword);
вынес в отдельный метод в сервисе, вызываю в контроллере перед сохранением

2023-08-15 08:41 UTC, Testov4 commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        if (id == null) {
по айдишнику проверяю едитим ли мы юзера или же он новосозданный(если эдитим, то ему соответственно можно оставить старый имейл и никнейм)

2023-08-15 08:49 UTC, Testov4 commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        userInformation.setUserId(user.getId());
удалил+поправил

2023-08-15 13:31 UTC, Testov4 commented on src/main/java/eshop/web/service/UserServiceImpl.java
> +        user.getUserInformation().setUser(user);
ubral

2023-08-15 13:31 UTC, Testov4 commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +    @Transactional
ой

2023-08-15 13:35 UTC, Testov4 commented on src/main/java/eshop/web/service/VendorServiceImpl.java
> +        if (vendorIsNew && (foundVendor != null)) {
done

2023-08-15 14:50 UTC, delusion4 commented on src/main/java/eshop/web/util/CategoryNotFoundException.java
> +import org.webjars.NotFoundException;
эээээ

2023-08-15 14:51 UTC, Testov4 commented on src/main/java/eshop/web/configuration/WebSecurityConfig.java
> +//
доне

2023-08-15 14:58 UTC, Testov4 commented on src/main/java/eshop/web/WebApplication.java
> +package eshop.web;
ну вроде сделал епт

2023-08-16 10:39 UTC, Testov4 commented on src/main/java/eshop/web/WebApplication.java
> +public class WebApplication {
добавил кал

2023-08-16 18:45 UTC, closed without merging