Dev
Testov4/web pull request #3
Opened 2023-08-16 18:46 UTC by Testov4

סובקו

2023-08-19 19:24 UTC, fartako requested changes

2023-08-19 19:24 UTC, fartako commented on src/main/resources/application.properties.origin
> +spring.datasource.password=
нихуя это не так делается, почитай про environment variables

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/util/UserValidator.java
> +    public void validate(Object target, Errors errors) {
почему обжект

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/util/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
почему Exception?

2023-08-19 19:24 UTC, fartako commented on src/main/resources/messages.properties
> +footer.city=Kharkiv, Ukraine
щееее не вмееерла украини

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/util/UserValidator.java
> +        if (userService.findUserByEmail(user.getEmail()) != null) {
нах эта проверка на налл

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/VendorServiceImpl.java
> +        return vendorRepository.findById(id).orElse(null);
хуйня

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/VendorServiceImpl.java
> +            .orElse(true);
сделай лучше

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +    private void assignUserInformationIfPresent(User user) {
эт концептуально кал, если метод что-то модифицирует то пусть он это и возвращает, не нужно стейт где-то в воздухе держать, потом заебешься дебажить

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +        log.info("connecting user information with user {} {}", user, userInformation);
каво коннектим

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +            .orElse(true);
плохо

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +            .orElse(true);
плохо

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +            orElseThrow(() -> new UsernameNotFoundException("User not found"));
переноси с точкой заебал

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +            .filter(p -> category == null || p.getCategory().equals(category))
зачем проверяешь на null?

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +            .orElse(true);
плохо

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +    public List<Product> findByNamePart(String name) {
переименуй

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/OrderServiceImpl.java
> +    private Double calculateFinalPrice(Product product ,Integer quantity) {
Деньги в дабле это кал

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/OrderServiceImpl.java
> +    public void changeOrdersStatus(List<Order> orders) {
по такой сигнатуре нихуя не понятно что этот метод оказывается чет в базе сохраняет

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/OrderServiceImpl.java
> +    public Order buildNewOrder(User user, Product product, String address, Integer quantity) {
убери new

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/MyUserDetailsService.java
> +package eshop.service;
почему в этом пакете

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/WebApplication.java
> +		SpringApplication.run(WebApplication.class, args);
не нашел миграций

2023-08-19 19:24 UTC, fartako commented on src/test/java/eshop/service/UserServiceImplTest.java
> +        return List.of(firstUser, secondUser);
убери кал воняет

2023-08-19 19:24 UTC, fartako commented on src/test/java/eshop/service/UserServiceImplTest.java
> +@ExtendWith(MockitoExtension.class)
ужас нах

2023-08-19 19:24 UTC, fartako commented on src/test/java/eshop/service/ProductServiceImplTest.java
> +public class ProductServiceImplTest {
мало тестов

2023-08-19 19:24 UTC, fartako commented on src/test/java/eshop/service/UserServiceImplTest.java
> +public class UserServiceImplTest {
мало тестов

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +            .filter(p -> category == null || p.getCategory().equals(category))
че будет если у продукта категория налл?

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +        List<Product> products = productRepository.findAll();
а если у тебя в базе миллиард продуктов то че будет?

2023-08-19 19:24 UTC, fartako commented on src/main/java/eshop/util/CategoryNotFoundException.java
> +package eshop.util;
почему все эти файлы лежат в утиле?

2023-08-19 19:24 UTC, fartako commented on src/main/resources/static/category-images/phones.png
замени айфоном

2023-08-19 19:24 UTC, fartako commented on src/main/resources/static/category-images/laptops.png
замени макбуками

2023-08-19 19:24 UTC, fartako commented on src/main/resources/static/category-images/watch.png
замени ми бендом

2023-08-19 19:24 UTC, fartako commented on src/test/java/eshop/WebApplicationTests.java
> +class WebApplicationTests {
удали если не используешь

2023-08-19 20:00 UTC, Testov4 commented on src/main/java/eshop/util/UserValidator.java
> +        if (userService.findUserByEmail(user.getEmail()) != null) {
убрал, теперь опшнл

2023-08-19 20:05 UTC, Testov4 commented on src/main/java/eshop/service/implementation/VendorServiceImpl.java
> +        return vendorRepository.findById(id).orElse(null);
done

2023-08-19 20:27 UTC, Testov4 commented on src/main/java/eshop/service/implementation/VendorServiceImpl.java
> +            .orElse(true);
s

2023-08-20 12:24 UTC, Testov4 commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +    private void assignUserInformationIfPresent(User user) {
vrode fixed

2023-08-20 12:25 UTC, Testov4 commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +        log.info("connecting user information with user {} {}", user, userInformation);
staroe nazVanie

2023-08-20 12:26 UTC, Testov4 commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +            .orElse(true);
done

2023-08-20 12:27 UTC, Testov4 commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +            orElseThrow(() -> new UsernameNotFoundException("User not found"));
done

2023-08-20 12:27 UTC, Testov4 commented on src/main/java/eshop/service/implementation/UserServiceImpl.java
> +            .orElse(true);
done

2023-08-20 12:42 UTC, Testov4 commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +            .filter(p -> category == null || p.getCategory().equals(category))
ээээ

2023-08-20 12:43 UTC, Testov4 commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +            .filter(p -> category == null || p.getCategory().equals(category))
теперь пустой листик

2023-08-20 12:43 UTC, Testov4 commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +            .orElse(true);
фиксед

2023-08-20 12:44 UTC, Testov4 commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +    public List<Product> findByNamePart(String name) {
done

2023-08-20 14:07 UTC, Testov4 commented on src/main/java/eshop/service/implementation/OrderServiceImpl.java
> +    public void changeOrdersStatus(List<Order> orders) {
ээ

2023-08-20 14:57 UTC, Testov4 commented on src/test/java/eshop/service/UserServiceImplTest.java
> +        return List.of(firstUser, secondUser);
вроде подтер попу

2023-08-20 15:20 UTC, Testov4 commented on src/main/java/eshop/service/implementation/ProductServiceImpl.java
> +        List<Product> products = productRepository.findAll();
пися в попе, врожде поменял

2023-08-20 16:02 UTC, Testov4 commented on src/main/java/eshop/util/CategoryNotFoundException.java
> +package eshop.util;
убрал в отдельный пакаж

2023-08-22 09:33 UTC, Testov4 commented on src/main/java/eshop/util/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
вроде как-то логично поменял

2023-08-22 09:35 UTC, Testov4 commented on src/main/java/eshop/util/UserValidator.java
> +    public void validate(Object target, Errors errors) {
У валидатора обжект

2023-08-22 10:38 UTC, Testov4 commented on src/main/resources/application.properties.origin
> +spring.datasource.password=
done

2023-08-22 11:49 UTC, Testov4 commented on src/test/java/eshop/service/ProductServiceImplTest.java
> +public class ProductServiceImplTest {
там нехуй тестить больше по идее

2023-08-22 12:37 UTC, Testov4 commented on src/test/java/eshop/service/UserServiceImplTest.java
> +public class UserServiceImplTest {
dobavil

2023-08-22 12:37 UTC, Testov4 commented on src/main/java/eshop/WebApplication.java
> +		SpringApplication.run(WebApplication.class, args);
ispravil

2023-08-22 12:38 UTC, closed without merging